version: "3"

services:
  postgres:
    image: postgres
    container_name: idemy_postgres
    env_file:
      - .env
    volumes:
      - idemy_postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_idemy:/var/lib/pgadmin

volumes:
  idemy_postgres:
  pgadmin_idemy:
